import test from "node:test";
import assert from "node:assert/strict";
import { nflSgoCategory } from "../lib/ai-mechanics/sgo-categories.js";
const row={periodID:"game",betTypeID:"ou",sideID:"over"};
test("SGO passing yard identifier",()=>assert.equal(nflSgoCategory({...row,marketName:"player_pass_yds"}),"passing_yards"));
test("SGO rushing yard identifier",()=>assert.equal(nflSgoCategory({...row,marketName:"player_rush_yds"}),"rushing_yards"));
test("SGO receiving yard identifier",()=>assert.equal(nflSgoCategory({...row,marketName:"player_reception_yds"}),"receiving_yards"));
test("SGO receptions identifier",()=>assert.equal(nflSgoCategory({...row,marketName:"player_receptions"}),"receptions"));
test("SGO anytime TD yes market",()=>assert.equal(nflSgoCategory({...row,marketName:"touchdown",statID:"touchdowns",betTypeID:"yn",sideID:"yes"}),"anytime_td"));
test("first half excluded",()=>assert.equal(nflSgoCategory({...row,marketName:"player_rush_yds",periodID:"1h"}),null));
test("under side excluded",()=>assert.equal(nflSgoCategory({...row,marketName:"player_rush_yds",sideID:"under"}),null));
test("unknown market excluded",()=>assert.equal(nflSgoCategory({...row,marketName:"team_spread"}),null));
