const SGO='https://api.sportsgameodds.com/v2/events';
const ESPN='https://site.api.espn.com/apis/site/v2/sports/football/nfl';
const NS={'Cache-Control':'no-store, no-cache, must-revalidate'};
const norm=x=>String(x||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
async function json(url,opts={}){const r=await fetch(url,{cache:'no-store',...opts});if(!r.ok)throw new Error('upstream_'+r.status);return r.json()}
function playerName(o){const explicit=o.statEntityName||o.playerName||o.player?.name||o.statEntity?.name;if(explicit)return explicit;const m=String(o.marketName||'').match(/^(.+?)\s+(?:To Record|Touchdowns?|Passing|Rushing|Receiving|Receptions?)/i);if(m)return m[1].trim();return String(o.statEntityID||'Unknown').replace(/_1_NFL$/i,'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,x=>x.toUpperCase())}
function market(o,eventID){const books=Object.entries(o.byBookmaker||{}).filter(([,v])=>v?.available).map(([book,v])=>({book,odds:v.odds??null,line:v.overUnder??v.spread??null}));return{eventID,playerID:o.playerID||o.statEntityID||'',name:playerName(o),marketName:o.marketName||'',statID:o.statID||'',periodID:o.periodID||'',betTypeID:o.betTypeID||'',sideID:o.sideID||'',fairOdds:o.fairOdds??null,bookOdds:o.bookOdds??null,line:o.bookOverUnder??null,books}}
function category(m){const s=(m.statID+' '+m.marketName).toLowerCase();if(m.periodID!=='game')return null;if(m.statID==='touchdowns'&&m.betTypeID==='yn'&&m.sideID==='yes')return'td';if(m.betTypeID!=='ou'||m.sideID!=='over')return null;if(s.includes('passing')&&s.includes('yard')&&!s.includes('rushing')&&!s.includes('receiving'))return'passing';if(s.includes('rushing')&&s.includes('yard')&&!s.includes('receiving')&&!s.includes('passing'))return'rushing';if(s.includes('receiving')&&s.includes('yard')&&!s.includes('rushing')&&!s.includes('passing'))return'receiving';if(s.includes('reception')&&!s.includes('yard')&&!s.includes('longest'))return'receptions';return null}
function americanToProb(a){a=+a;if(!Number.isFinite(a)||!a)return null;return a>0?100/(a+100):(-a)/(-a+100)}
function bestBook(m){const priced=m.books.filter(x=>Number.isFinite(+x.odds));const preferred=priced.filter(x=>['draftkings','fanduel'].includes(String(x.book).toLowerCase()));const pool=preferred.length?preferred:priced;return pool.sort((a,b)=>+b.odds-+a.odds)[0]||null}
function bookContext(m){return m.books.filter(x=>Number.isFinite(+x.odds)).sort((a,b)=>+b.odds-+a.odds).map(x=>({book:x.book,odds:+x.odds,line:x.line??null}))}
function score(m){const b=bestBook(m),p=americanToProb(b?.odds??m.bookOdds??m.fairOdds);return p??0}
function threshold(m){const b=bestBook(m),v=Number(b?.line??m.line);return Number.isFinite(v)?v:null}
function pickRows(rows,cat,limit=10){const x=rows.filter(m=>category(m)===cat);const by=new Map();for(const m of x){const k=m.playerID+'|'+cat,old=by.get(k);if(!old||score(m)>score(old))by.set(k,m)}return [...by.values()].sort((a,b)=>score(b)-score(a)).slice(0,limit).map((m,i)=>({rank:i+1,...m,threshold:threshold(m),confidence:Math.min(95,Math.round(score(m)*100)),bestBook:bestBook(m),sportsbooks:bookContext(m),reason:'Current full-game market, sportsbook price and threshold are used as betting context; Momentum Radar analytics determine the final projection and ranking.'}))}
function probToAmerican(p){if(!Number.isFinite(p)||p<=0||p>=1)return null;return Math.round(p>=.5?-100*p/(1-p):100*(1-p)/p)}
function parlayPrice(legs){const ps=legs.map(x=>americanToProb(x.bestBook?.odds??x.bookOdds??x.fairOdds)).filter(x=>Number.isFinite(x));if(ps.length!==legs.length)return null;const independent=ps.reduce((a,p)=>a*p,1);return probToAmerican(independent)}
function buildSgp(rows){const pool=[];for(const cat of ['td','passing','rushing','receiving','receptions'])for(const x of pickRows(rows,cat,8))pool.push({...x,cat});const clean=pool.filter(x=>!/(longest|quarter|half|first touchdown)/i.test(x.marketName||''));const make=(name,count,start)=>{const legs=[],used=new Set();for(const x of clean.slice(start).concat(clean.slice(0,start))){if(used.has(x.playerID))continue;used.add(x.playerID);legs.push(x);if(legs.length===count)break}const est=parlayPrice(legs);return{name,legs,estimatedOdds:est,oddsLabel:est==null?'Unavailable':'Estimated SGP Odds',pricing:'Independent-leg estimate from available sportsbook prices; actual same-game parlay price can differ because books apply correlation.'}};return[make('Small',2,0),make('Medium',3,2),make('Nuke',5,5)]}
async function allEvents(date){const key=process.env.SPORTSGAMEODDS_API_KEY;if(!key)throw new Error('missing_api_key');const u=new URL(SGO);u.searchParams.set('leagueID','NFL');u.searchParams.set('oddsAvailable','true');u.searchParams.set('limit','100');u.searchParams.set('startsAfter',date+'T00:00:00Z');const e=new Date(date+'T23:59:59Z');e.setUTCHours(e.getUTCHours()+6);u.searchParams.set('startsBefore',e.toISOString());const d=await json(u,{headers:{'x-api-key':key}});return Array.isArray(d?.data)?d.data:Array.isArray(d)?d:[]}
export default async function handler(req,res){Object.entries(NS).forEach(([k,v])=>res.setHeader(k,v));try{const gameId=String(req.query.gameId||''),date=String(req.query.date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return res.status(400).json({ok:false,error:'date_required'});let home='',away='';if(gameId){const s=await json(ESPN+'/summary?event='+encodeURIComponent(gameId));const cs=s.header?.competitions?.[0]?.competitors||[];home=cs.find(x=>x.homeAway==='home')?.team?.abbreviation||'';away=cs.find(x=>x.homeAway==='away')?.team?.abbreviation||''}const events=await allEvents(date);let chosen=events;if(gameId){chosen=events.filter(e=>{const h=e.teams?.home||{},a=e.teams?.away||{};const hs=[h.teamID,h.names?.short,h.names?.medium,h.names?.long].map(norm),as=[a.teamID,a.names?.short,a.names?.medium,a.names?.long].map(norm);return hs.includes(norm(home))&&as.includes(norm(away))})}const rows=chosen.flatMap(e=>Object.values(e.odds||{}).filter(o=>o&&!['all','home','away'].includes(String(o.statEntityID||'').toLowerCase())).map(o=>market(o,e.eventID||e.id)));const categories={};for(const c of ['td','passing','rushing','receiving','receptions'])categories[c]=pickRows(rows,c,10);const sgps=gameId?buildSgp(rows):[];return res.status(200).json({ok:true,scope:gameId?'game':'slate',gameId:gameId||null,date,categories,sgps,marketRows:rows.length,fetchedAt:new Date().toISOString()})}catch(e){return res.status(502).json({ok:false,error:String(e.message||e),fetchedAt:new Date().toISOString()})}}