import { put, list } from '@vercel/blob';
const SGO='https://api.sportsgameodds.com/v2/events';
const ESPN='https://site.api.espn.com/apis/site/v2/sports/football/nfl';
const ODDS='https://api.the-odds-api.com/v4/sports/americanfootball_nfl';
const NS={'Cache-Control':'no-store, no-cache, must-revalidate'};
const EDGE_GOOD='public, s-maxage=900, stale-while-revalidate=21600';
const norm=x=>String(x||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const CACHE=new Map(),TTL=15*60*1000,STALE=6*60*60*1000;
let GLOBAL_CACHE=null;
const LAST_CALL=new Map(),BACKOFF=new Map(),MIN_UPSTREAM_GAP=15*60*1000,RATE_BACKOFF=15*60*1000;
const SNAP_PREFIX='nfl-markets/v1/';
async function readSnapshot(date){try{const pathname=SNAP_PREFIX+date+'.json',x=await list({prefix:pathname,limit:5}),b=x.blobs?.find(v=>v.pathname===pathname);if(!b)return null;const r=await fetch(b.url,{cache:'no-store'});if(!r.ok)return null;const s=await r.json();return Array.isArray(s?.events)?{at:Number(s.at)||0,events:s.events}:null}catch{return null}}
async function writeSnapshot(date,events){try{await put(SNAP_PREFIX+date+'.json',JSON.stringify({at:Date.now(),events}),{access:'public',addRandomSuffix:false,allowOverwrite:true})}catch{}}
async function json(url,opts={},tries=3){let last;for(let i=0;i<tries;i++){try{const r=await fetch(url,{cache:'no-store',...opts});if(r.ok)return r.json();last=new Error('upstream_'+r.status);if(r.status===429){const retry=Number(r.headers.get('retry-after'));if(Number.isFinite(retry)&&retry>0)last.retryAfterSeconds=retry;throw last}if(![500,502,503,504].includes(r.status))throw last}catch(e){last=e;if(String(e.message||e)==='upstream_429')break}if(i<tries-1)await sleep(250*(i+1))}throw last}
function playerName(o){const explicit=o.statEntityName||o.playerName||o.player?.name||o.statEntity?.name;if(explicit)return explicit;const m=String(o.marketName||'').match(/^(.+?)\s+(?:To Record|Touchdowns?|Passing|Rushing|Receiving|Receptions?)/i);if(m)return m[1].trim().replace(/\s+Any$/i,'');return String(o.statEntityID||'Unknown').replace(/_1_NFL$/i,'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,x=>x.toUpperCase())}
function canonicalBook(x){x=String(x||'').toLowerCase().replace(/[^a-z]/g,'');if(x.includes('draftkings'))return'DraftKings';if(x.includes('fanduel'))return'FanDuel';return null}
function market(o,eventID){const books=Object.entries(o.byBookmaker||{}).filter(([,v])=>v?.available).map(([book,v])=>({book:canonicalBook(book)||book,odds:v.odds??null,line:v.overUnder??v.spread??null,available:true}));const rawTeam=o.teamID||o.team?.abbreviation||o.statEntity?.teamID||o.statEntity?.team?.abbreviation||'';return{eventID,playerID:o.playerID||o.statEntityID||'',name:playerName(o),team:norm(rawTeam),marketName:o.marketName||'',statID:o.statID||'',periodID:o.periodID||'',betTypeID:o.betTypeID||'',sideID:o.sideID||'',fairOdds:o.fairOdds??null,bookOdds:o.bookOdds??null,line:o.bookOverUnder??null,books}}
function category(m){const s=(m.statID+' '+m.marketName).toLowerCase();if(m.periodID!=='game')return null;if(m.statID==='touchdowns'&&m.betTypeID==='yn'&&m.sideID==='yes')return'td';if(m.betTypeID!=='ou'||m.sideID!=='over')return null;if(s.includes('passing')&&s.includes('yard')&&!s.includes('rushing')&&!s.includes('receiving'))return'passing';if(s.includes('rushing')&&s.includes('yard')&&!s.includes('receiving')&&!s.includes('passing'))return'rushing';if(s.includes('receiving')&&s.includes('yard')&&!s.includes('rushing')&&!s.includes('passing'))return'receiving';if(s.includes('reception')&&!s.includes('yard')&&!s.includes('longest'))return'receptions';return null}
function americanToProb(a){a=+a;if(!Number.isFinite(a)||!a)return null;return a>0?100/(a+100):(-a)/(-a+100)}
function bookFor(m,name){return m.books.find(x=>x.book===name&&Number.isFinite(+x.odds))||null}
function bestBook(m){return bookFor(m,'DraftKings')||bookFor(m,'FanDuel')||m.books.find(x=>Number.isFinite(+x.odds))||null}
function threshold(m){const b=bestBook(m),raw=b?.line??m.line;if(raw===null||raw===undefined||raw==='')return null;const v=Number(raw);return Number.isFinite(v)?v:null}
function reasonFor(m,cat){const b=bestBook(m);const book=b?.book||'market feed';const line=threshold(m);const base=cat==='td'?'Anytime-TD market is active':cat==='passing'?'Passing-yard market is active':cat==='rushing'?'Rushing-yard market is active':cat==='receiving'?'Receiving-yard market is active':'Reception market is active';return base+' at '+book+(line!=null?' with a '+line+' threshold':'')+'. Sportsbook availability is a validation gate only; odds are not used as Momentum scoring evidence.'}
function pickRows(rows,cat,limit=10){const x=rows.filter(m=>category(m)===cat&&(bookFor(m,'DraftKings')||bookFor(m,'FanDuel')));const by=new Map();for(const m of x){const k=m.playerID+'|'+cat,old=by.get(k);if(!old)by.set(k,m)}return[...by.values()].slice(0,limit).map((m,i)=>({rank:i+1,...m,threshold:threshold(m),confidence:null,bestBook:bestBook(m),sportsbooks:{DraftKings:bookFor(m,'DraftKings'),FanDuel:bookFor(m,'FanDuel')},verifiedAt:new Date().toISOString(),reason:reasonFor(m,cat)}))}
function probToAmerican(p){if(!Number.isFinite(p)||p<=0||p>=1)return null;return Math.round(p>=.5?-100*p/(1-p):100*(1-p)/p)}
function parlayPrice(legs,book){const ps=legs.map(x=>americanToProb(bookFor(x,book)?.odds)).filter(Number.isFinite);if(ps.length!==legs.length)return null;return probToAmerican(ps.reduce((a,p)=>a*p,1))}
function metricFor(cat){return cat==='passing'?'passYards':cat==='rushing'?'rushYards':cat==='receiving'?'recYards':cat==='receptions'?'receptions':cat==='td'?'recTD':null}
function positionFor(cat){return cat==='passing'?'QB':cat==='rushing'?'RB':cat==='receiving'?'WR':cat==='receptions'?'WR':null}
function momentumScore(x,ctx){
 const cat=x.cat,metric=metricFor(cat),pos=positionFor(cat);let score=50,signals=[];
 const offer=x.bookOffer||bestBook(x),marketProb=americanToProb(offer?.odds);
 if(cat==='td'&&marketProb!=null){score+=Math.max(-10,Math.min(10,(marketProb-.35)*35));signals.push('active TD market '+Math.round(marketProb*100)+'% implied')}
 const team=norm(x.team);if(team&&ctx?.opponents?.[team]&&metric&&pos){const def=ctx.opponents[team],r=Number(ctx.dvp?.defenseRanks?.[pos]?.[def]?.[metric]?.rankMost);if(Number.isFinite(r)){const adj=(r-16.5)/2;score+=adj;signals.push(def+' defense #'+r+' most '+metric+' allowed')}}
 if(offer&&Number.isFinite(+offer.line))signals.push('verified '+x.cat+' line '+offer.line);
 return{score:Math.max(1,Math.min(99,Math.round(score))),signals};
}
// SGP construction is market-gated: every leg must be an active offer at the named book.
// Momentum analytics may rank these eligible offers, but roster-only players never enter this pool.
function buildBookSgp(rows,book,ctx){const pool=[];for(const cat of ['td','passing','rushing','receiving','receptions'])for(const m of rows.filter(x=>category(x)===cat&&bookFor(x,book))){const base={...m,cat,bookOffer:bookFor(m,book)},mom=momentumScore(base,ctx);pool.push({...base,momentumScore:mom.score,momentumSignals:mom.signals})}pool.sort((a,b)=>b.momentumScore-a.momentumScore);const make=(risk,count,offset)=>{const legs=[],used=new Set();for(const x of pool.slice(offset).concat(pool.slice(0,offset))){if(used.has(x.playerID))continue;used.add(x.playerID);legs.push(x);if(legs.length===count)break}const est=parlayPrice(legs,book),avg=legs.length?Math.round(legs.reduce((s,x)=>s+x.momentumScore,0)/legs.length):null;return{book,risk,legs,estimatedOdds:est,momentumScore:avg,verifiedAt:new Date().toISOString(),reason:legs.length?('Every leg is currently verified on '+book+' and ranked by Momentum matchup signals before SGP construction.'):'No fully verified '+book+' SGP is available right now.'}};return[make('Small',3,0),make('Medium',4,1),make('Nuke',5,2)]}
function oddsApiCategory(k){return k==='player_anytime_td'?'td':k==='player_pass_yds'||k==='player_pass_yds_alternate'?'passing':k==='player_rush_yds'||k==='player_rush_yds_alternate'?'rushing':k==='player_reception_yds'||k==='player_reception_yds_alternate'?'receiving':k==='player_receptions'||k==='player_receptions_alternate'?'receptions':null}
function oddsApiRows(d,eventID){
 const out=[];
 for(const b of d?.bookmakers||[]){const book=canonicalBook(b.key||b.title);if(!book)continue;for(const mk of b.markets||[]){const cat=oddsApiCategory(mk.key);if(!cat)continue;for(const o of mk.outcomes||[]){const side=String(o.description||o.name||'');const isTD=cat==='td',isOver=String(o.name||'').toLowerCase()==='over';if(!isTD&&!isOver)continue;const name=isTD?String(o.description||''):side;if(!name)continue;out.push({eventID,playerID:norm(name),name,team:'',marketName:mk.key,statID:cat==='td'?'touchdowns':mk.key,periodID:'game',betTypeID:isTD?'yn':'ou',sideID:isTD?'yes':'over',fairOdds:null,bookOdds:o.price??null,line:o.point??null,books:[{book,odds:o.price??null,line:o.point??null,available:true}],provider:'The Odds API'})}}}return out
}
async function oddsApiFallback(date,home,away){
 const key=process.env.THE_ODDS_API_KEY;if(!key)return null;
 const er=await fetch(ODDS+'/events?apiKey='+encodeURIComponent(key)+'&dateFormat=iso',{cache:'no-store'});if(!er.ok)throw Error('odds_api_events_'+er.status);const events=await er.json();
 const aliases={ATL:['ATL','ATLANTA','ATLANTAFALCONS'],GB:['GB','GREENBAY','GREENBAYPACKERS']};const match=(name,abbr)=>(aliases[norm(abbr)]||[norm(abbr)]).includes(norm(name));
 const ev=(events||[]).find(x=>match(x.home_team,home)&&match(x.away_team,away));if(!ev)return [];
 const markets=['player_anytime_td','player_pass_yds','player_rush_yds','player_reception_yds','player_receptions'].join(',');
 const u=ODDS+'/events/'+encodeURIComponent(ev.id)+'/odds?apiKey='+encodeURIComponent(key)+'&regions=us&bookmakers=draftkings,fanduel&markets='+markets+'&oddsFormat=american';
 const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('odds_api_markets_'+r.status);return oddsApiRows(await r.json(),ev.id)
}
async function allEvents(date){let cached=CACHE.get(date)||GLOBAL_CACHE,now=Date.now();if(!cached){cached=await readSnapshot(date);if(cached){CACHE.set(date,cached);GLOBAL_CACHE=cached}}if(cached&&now-cached.at<TTL)return cached.events;if(cached&&now-(LAST_CALL.get(date)||0)<MIN_UPSTREAM_GAP)return cached.events;const blockedUntil=BACKOFF.get(date)||0;if(now<blockedUntil){if(cached&&now-cached.at<STALE)return cached.events;const err=new Error('sportsbook_rate_limited_no_snapshot');err.retryAfterSeconds=Math.ceil((blockedUntil-now)/1000);throw err}const key=process.env.SPORTSGAMEODDS_API_KEY;if(!key)throw new Error('missing_api_key');const u=new URL(SGO);u.searchParams.set('leagueID','NFL');u.searchParams.set('oddsAvailable','true');u.searchParams.set('limit','100');u.searchParams.set('startsAfter',date+'T00:00:00Z');const e=new Date(date+'T23:59:59Z');e.setUTCHours(e.getUTCHours()+6);u.searchParams.set('startsBefore',e.toISOString());let events;LAST_CALL.set(date,now);try{const d=await json(u,{headers:{'x-api-key':key}},3);events=Array.isArray(d?.data)?d.data:Array.isArray(d)?d:[];CACHE.set(date,{at:Date.now(),events});GLOBAL_CACHE={at:Date.now(),events};await writeSnapshot(date,events);BACKOFF.delete(date);return events}catch(e){if(String(e.message||e).includes('upstream_429'))BACKOFF.set(date,Date.now()+Math.max(RATE_BACKOFF,(Number(e.retryAfterSeconds)||0)*1000));if(cached&&now-cached.at<STALE)return cached.events;if(String(e.message||e).includes('upstream_429')){const err=new Error('sportsbook_rate_limited_no_snapshot');err.retryAfterSeconds=Math.ceil(Math.max(RATE_BACKOFF,(Number(e.retryAfterSeconds)||0)*1000)/1000);throw err}throw e}}
export default async function handler(req,res){Object.entries(NS).forEach(([k,v])=>res.setHeader(k,v));try{const gameId=String(req.query.gameId||''),date=String(req.query.date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return res.status(400).json({ok:false,error:'date_required'});let home='',away='';if(gameId){const s=await json(ESPN+'/summary?event='+encodeURIComponent(gameId));const cs=s.header?.competitions?.[0]?.competitors||[];home=cs.find(x=>x.homeAway==='home')?.team?.abbreviation||'';away=cs.find(x=>x.homeAway==='away')?.team?.abbreviation||''}let events,provider='SportsGameOdds',directRows=null;try{events=await allEvents(date)}catch(primaryErr){events=[]}
 if(gameId&&home&&away){let primaryRows=[];if(events.length){const pe=events.filter(e=>{const h=e.teams?.home||{},a=e.teams?.away||{};return [h.teamID,h.names?.short,h.names?.medium,h.names?.long].map(norm).includes(norm(home))&&[a.teamID,a.names?.short,a.names?.medium,a.names?.long].map(norm).includes(norm(away))});primaryRows=pe.flatMap(e=>Object.values(e.odds||{}).filter(o=>o&&!['all','home','away'].includes(String(o.statEntityID||'').toLowerCase())).map(o=>market(o,e.eventID||e.id)))}
 if(!primaryRows.some(m=>bookFor(m,'DraftKings')||bookFor(m,'FanDuel'))){const alt=await oddsApiFallback(date,home,away);if(alt!==null){directRows=alt;provider='The Odds API'}}}let chosen=events;if(gameId)chosen=events.filter(e=>{const h=e.teams?.home||{},a=e.teams?.away||{};const hs=[h.teamID,h.names?.short,h.names?.medium,h.names?.long].map(norm),as=[a.teamID,a.names?.short,a.names?.medium,a.names?.long].map(norm);return hs.includes(norm(home))&&as.includes(norm(away))});const rows=directRows||chosen.flatMap(e=>Object.values(e.odds||{}).filter(o=>o&&!['all','home','away'].includes(String(o.statEntityID||'').toLowerCase())).map(o=>market(o,e.eventID||e.id)));const categories={};for(const c of ['td','passing','rushing','receiving','receptions'])categories[c]=pickRows(rows,c,10);let ctx={opponents:{},dvp:null};if(gameId&&home&&away){ctx.opponents[norm(home)]=norm(away);ctx.opponents[norm(away)]=norm(home);try{const season=Number(chosen?.[0]?.season)||new Date().getUTCFullYear(),week=Number(chosen?.[0]?.week)||1;const base=(req.headers['x-forwarded-proto']||'https')+'://'+req.headers.host;const dr=await fetch(base+'/api/nfl-dvp?season='+season+'&week='+week+'&teams='+encodeURIComponent(home+','+away),{cache:'no-store'});if(dr.ok)ctx.dvp=await dr.json()}catch{}}const sgps=gameId?{DraftKings:buildBookSgp(rows,'DraftKings',ctx),FanDuel:buildBookSgp(rows,'FanDuel',ctx)}:{};res.setHeader('Cache-Control',EDGE_GOOD);res.setHeader('CDN-Cache-Control',EDGE_GOOD);res.setHeader('Vercel-CDN-Cache-Control',EDGE_GOOD);return res.status(200).json({ok:true,scope:gameId?'game':'slate',gameId:gameId||null,date,categories,sgps,provider,validation:{books:['DraftKings','FanDuel'],providers:['SportsGameOdds','The Odds API'],marketSpecific:true,refreshMinutes:15,rule:'A player/leg must have an active matching market at the named sportsbook. Popularity is never a scoring input.'},marketRows:rows.length,fetchedAt:new Date().toISOString()})}catch(e){const msg=String(e.message||e),rate=msg.includes('sportsbook_rate_limited');if(rate)res.setHeader('Retry-After',String(e.retryAfterSeconds||900));return res.status(rate?503:502).json({ok:false,error:msg,retryable:rate||/upstream_(429|5\d\d)/.test(msg),degraded:rate,fetchedAt:new Date().toISOString()})}}