import { put, list } from '@vercel/blob';
const P='nfl-pregame/v1';
const SGO='https://api.sportsgameodds.com/v2/events';
function path(gameId){return P+'/'+gameId+'.json'}
export async function read(gameId){const x=await list({prefix:path(gameId),limit:5});const b=x.blobs?.find(v=>v.pathname===path(gameId));if(!b)return null;const r=await fetch(b.url,{cache:'no-store'});return r.ok?r.json():null}
async function json(u,o={}){const r=await fetch(u,{cache:'no-store',...o});if(!r.ok)throw Error('upstream_'+r.status);return r.json()}
function prob(a){a=+a;if(!Number.isFinite(a)||!a)return 0;return a>0?100/(a+100):(-a)/(-a+100)}
function pname(o){const e=o.statEntityName||o.playerName||o.player?.name||o.statEntity?.name;if(e)return e;const m=String(o.marketName||'').match(/^(.+?)\s+(?:To Record|Touchdowns?)/i);return (m?.[1]||String(o.statEntityID||'Unknown').replace(/_1_NFL$/i,'').replaceAll('_',' ')).trim().replace(/\s+Any$/i,'')}
async function tdBoard(date){const key=process.env.SPORTSGAMEODDS_API_KEY;if(!key)throw Error('missing_api_key');const u=new URL(SGO);u.searchParams.set('leagueID','NFL');u.searchParams.set('oddsAvailable','true');u.searchParams.set('limit','100');u.searchParams.set('startsAfter',date+'T00:00:00Z');const e=new Date(date+'T23:59:59Z');e.setUTCHours(e.getUTCHours()+6);u.searchParams.set('startsBefore',e.toISOString());const d=await json(u,{headers:{'x-api-key':key}}),events=Array.isArray(d?.data)?d.data:Array.isArray(d)?d:[];const rows=[];for(const ev of events)for(const o of Object.values(ev.odds||{})){if(o?.statID!=='touchdowns'||o.periodID!=='game'||o.betTypeID!=='yn'||o.sideID!=='yes')continue;const books=Object.entries(o.byBookmaker||{}).filter(([,v])=>v?.available&&Number.isFinite(+v.odds)).map(([book,v])=>({book,odds:+v.odds}));if(!books.length)continue;const preferred=books.filter(x=>['draftkings','fanduel'].includes(x.book.toLowerCase())),pool=preferred.length?preferred:books,best=pool.sort((a,b)=>b.odds-a.odds)[0];rows.push({gameId:null,eventID:ev.eventID||ev.id,playerId:String(o.playerID||o.statEntityID||''),name:pname(o),market:'anytime_td',bestBook:best,sportsbooks:books,marketProbability:Math.round(prob(best.odds)*100)})}const by=new Map();for(const x of rows){const old=by.get(x.playerId);if(!old||x.marketProbability>old.marketProbability)by.set(x.playerId,x)}return [...by.values()].sort((a,b)=>b.marketProbability-a.marketProbability).slice(0,10)}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');const gameId=String(req.query.gameId||'');if(req.method==='GET'){if(!gameId)return res.status(400).json({available:false,error:'gameId_required'});const s=await read(gameId);return res.status(s?200:404).json(s?{available:true,snapshot:s}:{available:false,reason:'no_verified_pregame_snapshot'})}if(req.method==='POST'){const date=String(req.query.date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return res.status(400).json({ok:false,error:'date_required'});const existing=await list({prefix:P+'/slate-'+date+'.json',limit:5});if(existing.blobs?.length)return res.status(409).json({ok:false,error:'snapshot_already_locked'});const picks=await tdBoard(date);const snap={version:1,date,lockedAt:new Date().toISOString(),source:'sportsbook_market_context',modelVerified:false,picks,note:'Locked sportsbook-context board. Stars require exact player IDs and this snapshot does not claim Momentum Radar model verification.'};await put(P+'/slate-'+date+'.json',JSON.stringify(snap),{access:'public',addRandomSuffix:false});return res.status(201).json({ok:true,snapshot:snap})}return res.status(405).json({available:false,error:'method_not_allowed'})}