import { gradeHistory, parlayStatus } from '../lib/nfl-results.js';
import { put, list } from '@vercel/blob';
const ESPN="https://site.api.espn.com/apis/site/v2/sports/football/nfl";
const ESPN_STATS="https://site.web.api.espn.com/apis/common/v3/sports/football/nfl/statistics/byathlete";
const ESPN_INJ="https://site.api.espn.com/apis/site/v2/sports/football/nfl/injuries";
const HISTORY_PREFIX='momentum-history/v1/nfl-';
const noStore={"Cache-Control":"no-store, max-age=0","Pragma":"no-cache"};
async function json(url){const r=await fetch(url,{headers:{"accept":"application/json"}});if(!r.ok)throw new Error("upstream_"+r.status);return r.json()}
async function projections(competitors,blockedIds=new Set()){
 const out=[];
 for(const c of competitors){const team=c.team||{},abbr=String(team.abbreviation||'').toUpperCase(),teamKey=abbr||String(team.id||'');if(!teamKey)continue;try{let d;try{d=await json(ESPN+'/teams/'+encodeURIComponent(teamKey)+'/roster')}catch{d=await json(ESPN+'/teams/'+encodeURIComponent(teamKey)+'?enable=roster')}const groups=Array.isArray(d.athletes)?d.athletes:Array.isArray(d.team?.athletes)?d.team.athletes:Array.isArray(d.team?.roster?.athletes)?d.team.roster.athletes:Array.isArray(d.roster?.athletes)?d.roster.athletes:Array.isArray(d.items)?d.items:[];const rows=groups.flatMap(g=>Array.isArray(g.items)?g.items:Array.isArray(g.athletes)?g.athletes:Array.isArray(g.positions)?g.positions.flatMap(p=>p.items||p.athletes||[]):(g.id||g.displayName||g.fullName)?[g]:[]);for(const a of rows){const pos=a.position?.abbreviation||a.position?.name||null;if(!['QB','RB','WR','TE'].includes(pos)||blockedIds.has(String(a.id||'')))continue;out.push({playerId:String(a.id||''),name:a.displayName||a.fullName||a.name||'Unknown',team:abbr,position:pos,stats:[],source:'ESPN current team roster',rosterOnly:true})}}catch(e){}}
 const balanced=[]; for(const c of competitors){const abbr=String(c.team?.abbreviation||'').toUpperCase();balanced.push(...out.filter(x=>x.team===abbr))} return balanced;
}

function normalizeName(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function resolveRoleSignals(summary,rosterCandidates,blockedIds){const signals=[];const push=(name,team,status,source,kind='STRUCTURED')=>{if(name)signals.push({name,team:team||null,status,source,kind,checkedAt:new Date().toISOString()})};for(const t of summary.rosters||[]){const team=String(t.team?.abbreviation||'').toUpperCase();for(const r of t.roster||t.athletes||[]){const a=r.athlete||r,starter=r.starter===true||r.isStarter===true||String(r.role||r.status?.type?.name||'').toLowerCase().includes('starter');if(starter)push(a.displayName||a.fullName,team,'CONFIRMED_STARTER','ESPN game roster starter flag')}}for(const c of rosterCandidates){if(blockedIds.has(c.playerId))continue;const s=signals.find(x=>normalizeName(x.name)===normalizeName(c.name)&&(x.team==null||x.team===c.team));if(s)c._roleSignal=s}return signals}
function applyExpectedStarterEvidence(rosterCandidates,blockedIds,evidence=[]){const accepted=[];for(const e of evidence){if(!e||!['NFL_OFFICIAL','TEAM_OFFICIAL'].includes(String(e.authority||''))||!['EXPECTED_STARTER','CONFIRMED_STARTER'].includes(String(e.status||'')))continue;const p=rosterCandidates.find(x=>normalizeName(x.name)===normalizeName(e.name)&&(!e.team||String(x.team).toUpperCase()===String(e.team).toUpperCase()));if(!p||blockedIds.has(p.playerId))continue;p._roleSignal={name:p.name,team:p.team,status:e.status,source:e.source||e.authority,kind:'REPORTED_CURRENT_GAME',checkedAt:e.checkedAt||new Date().toISOString()};accepted.push(p._roleSignal)}return accepted}

const VERIFIED_GAME_ROLE_EVIDENCE={
 '401872963':[
  {name:'Case Keenum',team:'CHI',status:'EXPECTED_STARTER',authority:'NFL_OFFICIAL',source:'NFL Network / NFL.com — Ian Rapoport, 2026-09-28',checkedAt:'2026-09-28T11:32:00Z'},
  {name:'Jalen Hurts',team:'PHI',status:'CONFIRMED_STARTER',authority:'TEAM_OFFICIAL',source:'Philadelphia Eagles current game roster / QB1 cross-check',checkedAt:'2026-09-28T20:00:00Z'}
 ],
 '401872964':[
  {name:'Aaron Rodgers',team:'PIT',status:'CONFIRMED_STARTER',authority:'NFL_OFFICIAL',source:'NFL.com Week 4 Steelers-Browns game center / QB leader, 2026-10-01',checkedAt:'2026-10-01T16:00:00Z'},
  {name:'Deshaun Watson',team:'CLE',status:'CONFIRMED_STARTER',authority:'NFL_OFFICIAL',source:'NFL.com Week 4 Steelers-Browns game center / QB leader, 2026-10-01',checkedAt:'2026-10-01T16:00:00Z'},
  {name:'Jaylen Warren',team:'PIT',status:'EXPECTED_STARTER',authority:'NFL_OFFICIAL',source:'NFL.com Week 4 preview: Warren primary workload with Rico Dowdle out, 2026-10-01',checkedAt:'2026-10-01T16:00:00Z'},
  {name:'Quinshon Judkins',team:'CLE',status:'EXPECTED_STARTER',authority:'NFL_OFFICIAL',source:'NFL.com Week 4 preview: Judkins-led running game, 2026-10-01',checkedAt:'2026-10-01T16:00:00Z'},
  {name:'Denzel Boston',team:'CLE',status:'EXPECTED_STARTER',authority:'NFL_OFFICIAL',source:'NFL.com Week 4 preview / current receiving leader, 2026-10-01',checkedAt:'2026-10-01T16:00:00Z'},
  {name:'Harold Fannin Jr.',team:'CLE',status:'EXPECTED_STARTER',authority:'NFL_OFFICIAL',source:'NFL.com Week 4 preview: featured young tight end, 2026-10-01',checkedAt:'2026-10-01T16:00:00Z'}
 ]
};
function verifiedGameEvidence(gameId){return VERIFIED_GAME_ROLE_EVIDENCE[String(gameId)]||[]}

const statusMap=s=>{const x=String(s||"").toLowerCase();if(x.includes("out"))return"OUT";if(x.includes("doubt"))return"DOUBTFUL";if(x.includes("question"))return"QUESTIONABLE";if(x.includes("injured reserve")||x==="ir")return"IR";return x?"ACTIVE":"UNKNOWN"};

const hnum=v=>{const n=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null};
async function readHistory(gameId){try{const path=HISTORY_PREFIX+gameId+'.json',x=await list({prefix:path,limit:5}),b=x.blobs?.find(v=>v.pathname===path);if(!b)return null;const r=await fetch(b.url,{cache:'no-store'});return r.ok?r.json():null}catch{return null}}
async function listHistory(){try{const x=await list({prefix:HISTORY_PREFIX,limit:100});const rows=await Promise.all((x.blobs||[]).map(async b=>{try{const r=await fetch(b.url,{cache:'no-store'});return r.ok?r.json():null}catch{return null}}));return rows.filter(Boolean).sort((a,b)=>String(b.lockedAt||'').localeCompare(String(a.lockedAt||'')))}catch{return[]}}
async function lockHistory(gameId,body){const prior=await readHistory(gameId),kickoff=Date.parse(body.game?.kickoff),now=Date.now();if(!Number.isFinite(kickoff)||kickoff<=now)throw Error('pregame_only');if(!(body.picks?.length||body.sgps?.some(s=>s.legs?.length)))throw Error('empty_snapshot');const ms=kickoff-now,stage=ms<=30*60000?'FINAL_T_MINUS_30':ms<=90*60000?'PREGAME_VALIDATION':'EARLY_PREGAME',snap={league:'nfl',gameId,lockedAt:new Date().toISOString(),firstLockedAt:prior?.firstLockedAt||prior?.lockedAt||new Date().toISOString(),revision:Number(prior?.revision||0)+1,lockStage:stage,game:body.game||null,picks:body.picks||[],sgps:body.sgps||[]};await put(HISTORY_PREFIX+gameId+'.json',JSON.stringify(snap),{access:'public',addRandomSuffix:false,allowOverwrite:true});return snap}
function finalStats(summary){const out=new Map();for(const team of summary.boxscore?.players||[])for(const group of team.statistics||[]){const labels=(group.labels||group.names||[]).map(x=>String(x).toUpperCase()),gn=String(group.name||group.displayName||'').toLowerCase();for(const row of group.athletes||[]){const id=String(row.athlete?.id||row.id||'');if(!id)continue;const o=out.get(id)||{},m={};labels.forEach((k,i)=>m[k]=hnum(row.stats?.[i]));if(gn.includes('passing'))o.passing=m.YDS;if(gn.includes('rushing')){o.rushing=m.YDS;o.rushTD=m.TD}if(gn.includes('receiv')){o.receptions=m.REC;o.receiving=m.YDS;o.recTD=m.TD}out.set(id,o)}}return out}


export default async function handler(req,res){
 Object.entries(noStore).forEach(([k,v])=>res.setHeader(k,v));
 if(!['GET','POST'].includes(req.method))return res.status(405).json({ok:false,error:'method_not_allowed'});if(req.method==='GET'&&String(req.query.mode||'')==='history-list')return res.status(200).json({ok:true,history:await listHistory()}); const gameId=String(req.query.gameId||req.body?.gameId||""); if(!gameId)return res.status(400).json({ok:false,error:"gameId_required"});if(req.method==='POST'&&req.body?.action==='lock-history'){try{return res.status(200).json({ok:true,locked:await lockHistory(gameId,req.body)})}catch(e){return res.status(502).json({ok:false,error:'history_lock_failed'})}}
 try{
  const summary=await json(`${ESPN}/summary?event=${encodeURIComponent(gameId)}`);
  const comp=summary.header?.competitions?.[0]||{}; const competitors=comp.competitors||[];
  const allowedIds=new Set(competitors.map(c=>String(c.team?.id||"")).filter(Boolean)); const allowedAbbr=new Set(competitors.map(c=>String(c.team?.abbreviation||"").toUpperCase()).filter(Boolean));
  let injuryGroups=summary.injuries||[];if(!injuryGroups.length){try{const leagueInj=await json(ESPN_INJ);injuryGroups=leagueInj.injuries||leagueInj.items||[]}catch(e){}}
  const injuries=(injuryGroups||[]).filter(team=>allowedIds.has(String(team.team?.id||""))||allowedAbbr.has(String(team.team?.abbreviation||"").toUpperCase())).flatMap(team=>(team.injuries||[]).map(i=>({
    team:team.team?.abbreviation||team.team?.displayName||null,playerId:String(i.athlete?.id||""),name:i.athlete?.displayName||i.athlete?.fullName||"Unknown",
    position:i.athlete?.position?.abbreviation||null,injury:i.details?.type||i.type?.description||i.details?.detail||null,
    status:statusMap(i.status||i.details?.status),rawStatus:i.status||i.details?.status||null,source:"ESPN game summary"
  })));
  const athleteTeam=new Map(); for(const t of (summary.rosters||[])){const ta=String(t.team?.abbreviation||"").toUpperCase();for(const a of (t.roster||t.athletes||[])){const id=String(a.athlete?.id||a.id||"");if(id)athleteTeam.set(id,ta)}}
  const scopedInjuries=injuries.filter(x=>allowedAbbr.has(String(x.team||"").toUpperCase())||allowedAbbr.has(athleteTeam.get(x.playerId)||""));
  const blockers=scopedInjuries.filter(x=>["OUT","DOUBTFUL","IR"].includes(x.status));const questionableIds=new Set(scopedInjuries.filter(x=>x.status==="QUESTIONABLE").map(x=>x.playerId));
  const teams=competitors.map(c=>({id:String(c.team?.id||""),abbr:c.team?.abbreviation,name:c.team?.displayName,homeAway:c.homeAway}));
  if(String(req.query.mode||'')==='history-grade'){const locked=await readHistory(gameId),stats=finalStats(summary),final=String(comp.status?.type?.state||'').toLowerCase()==='post'||/final/i.test(String(comp.status?.type?.description||'')),score=competitors.map(c=>({team:c.team?.abbreviation||'',homeAway:c.homeAway,score:hnum(c.score)})),picks=(locked?.picks||[]).map(p=>({...p,grade:gradeHistory(p,stats)})),sgps=(locked?.sgps||[]).map(s=>{const legs=(s.legs||[]).map(p=>({...p,grade:gradeHistory(p,stats)}));return{...s,legs,legsHit:legs.filter(x=>x.grade.status==='HIT').length,legsTotal:legs.length,status:parlayStatus(legs),hit:parlayStatus(legs)==='HIT'}});return res.status(200).json({ok:true,gameId,final,teams:score,picks,sgps,lockedAt:locked?.lockedAt||null,gradedAt:new Date().toISOString()})}
  const blockedIds=new Set(blockers.map(x=>String(x.playerId||'')).filter(Boolean));const rosterCandidates=await projections(competitors,blockedIds);const roleSignals=resolveRoleSignals(summary,rosterCandidates,blockedIds);for(const p of rosterCandidates){if(blockedIds.has(p.playerId)||p._roleSignal)continue;const pos=String(p.position||'').toUpperCase();if(!['QB','RB','WR','TE'].includes(pos))continue;const u=Number(p.usagePerGame?.targets||0)+Number(p.usagePerGame?.rushAttempts||0);if((pos==='QB'&&Number(p.gamesPlayed||0)>0)||u>=3)p._roleSignal={name:p.name,team:p.team,status:'HIGH_USAGE_ROLE',source:'ESPN current roster + completed-game usage',kind:'DATA_VERIFIED_ROLE',checkedAt:new Date().toISOString()}}const suppliedRoleEvidence=Array.isArray(req.body?.roleEvidence)?req.body.roleEvidence:[];const currentGameEvidence=[...verifiedGameEvidence(gameId),...suppliedRoleEvidence];roleSignals.push(...applyExpectedStarterEvidence(rosterCandidates,blockedIds,currentGameEvidence));const injuryById=new Map(scopedInjuries.map(x=>[String(x.playerId||''),x]));const playerProjections=rosterCandidates.map(x=>{const inj=injuryById.get(x.playerId),availability=questionableIds.has(x.playerId)?'QUESTIONABLE':'ACTIVE_ROTATION';return{...x,availability,starterVerified:!!x._roleSignal,starterStatus:x._roleSignal?.status||'UNVERIFIED_ROLE',recommendationEligible:!!x._roleSignal,verification:{availability:{verified:true,status:availability,source:inj?.source||'ESPN current game/roster cross-check',checkedAt:new Date().toISOString()},role:{verified:!!x._roleSignal,status:x._roleSignal?.status||'UNVERIFIED_ROLE',source:x._roleSignal?.source||null,checkedAt:new Date().toISOString()},sportsbook:{verified:false,status:'PENDING_MARKET_MATCH',source:null,checkedAt:null}},evidence:['ESPN current team roster','ESPN game injury cross-check'],rule:'Availability never implies starter status. Starter role requires independent current-game role evidence.'}});
  return res.status(200).json({ok:true,gameId,teams,injuries:scopedInjuries,blockers,roleSignals,playerProjections,eligibility:{ready:true,state:"ROLE_RECONCILIATION_REQUIRED",failClosed:true,requiredEvidence:["availability","gameRole","sportsbookMarket"],reason:"Roster membership, practice participation, and active status never independently verify a starter. Starter-dependent recommendations require separate current-game role evidence plus current injury/inactive validation and sportsbook market verification."},fetchedAt:new Date().toISOString(),source:"ESPN roster/injury cross-check; official NFL/team game status and sportsbook market evidence are required before starter-dependent recommendations"});
 }catch(e){return res.status(502).json({ok:false,gameId,error:e.message,fetchedAt:new Date().toISOString()})}
}