import { read as readPregame } from './nfl-pregame.js';
const ESPN='https://site.api.espn.com/apis/site/v2/sports/football/nfl/summary';
const NS='no-store, no-cache, must-revalidate';
async function json(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('upstream_'+r.status);return r.json()}
function scorerAbbr(txt){let m=txt.match(/\bpass\b[\s\S]*?\bto\s+([A-Z]\.[A-Za-z][A-Za-z.'-]*)\s+for\s+[\d-]+\s+yards?,\s*TOUCHDOWN/i);if(m)return m[1];m=txt.match(/(?:^|\)\s)([A-Z]\.[A-Za-z][A-Za-z.'-]*)\s+(?:left|right|up|scrambles)\b[\s\S]*?TOUCHDOWN/i);return m?.[1]||''}
function rosterIndex(d){const out=[];for(const t of (d.rosters||[]))for(const r of (t.roster||t.athletes||[])){const a=r.athlete||r;if(a?.id)out.push(a)}return out}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z]/g,'')}
function resolvePlayer(d,abbr){if(!abbr)return null;const [ini,last]=abbr.split('.');const ni=norm(ini),nl=norm(last);return rosterIndex(d).find(a=>{const full=String(a.displayName||a.fullName||'').trim().split(/\s+/),first=full[0]||'',surname=full.slice(1).join('');return norm(first).startsWith(ni)&&norm(surname).endsWith(nl)})||null}
function tdRows(d){const out=[],seen=new Set();for(const drive of (d.drives?.previous||[])){for(const p of (drive.plays||[])){if(!p.scoringPlay)continue;const txt=String(p.text||'');if(!/touchdown/i.test(txt))continue;const abbr=scorerAbbr(txt).trim();const parts=(p.participants||[]).map(x=>x.athlete).filter(Boolean);const a=parts.find(x=>abbr&&String(x.shortName||x.abbreviation||'').toLowerCase()===abbr.toLowerCase())||parts.find(x=>abbr&&String(x.displayName||'').split(' ').some(n=>abbr.toLowerCase().endsWith(n.toLowerCase())))||resolvePlayer(d,abbr);const name=a?.displayName||abbr||'Touchdown scorer';const playerId=String(a?.id||'');const key=String(p.id||name+'|'+txt);if(seen.has(key))continue;seen.add(key);out.push({playId:p.id||null,playerId,name,text:txt,period:p.period?.number||null,clock:p.clock?.displayValue||null})}}return out}
export default async function handler(req,res){res.setHeader('Cache-Control',NS);if(req.method!=='GET')return res.status(405).json({ok:false,error:'method_not_allowed'});const gameId=String(req.query.gameId||'');if(!gameId)return res.status(400).json({ok:false,error:'gameId_required'});try{const d=await json(ESPN+'?event='+encodeURIComponent(gameId));const pre=await readPregame(gameId).catch(()=>null);const ids=new Set((pre?.picks||pre?.players||[]).map(x=>String(x.playerId||x.playerID||'')));const touchdowns=tdRows(d).map(x=>({...x,star:!!x.playerId&&ids.has(x.playerId)}));return res.status(200).json({ok:true,gameId,status:d.header?.competitions?.[0]?.status?.type?.description||null,touchdowns,pregameSnapshot:!!pre,fetchedAt:new Date().toISOString()})}catch(e){return res.status(503).json({ok:false,error:'nfl_live_unavailable',detail:String(e.message||e)})}}